spring: 
    profiles: 
    active: 
    - dev
---
spring:
    profiles: dev   #开发环境
    application: 
        name: fenjin-services-cloud-config-dev

---
spring:
    profiles: test   #开发环境
    application: 
        name: fenjin-services-cloud-config-test
        
# 请保存为UTF-8格式